version: '3.7'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 9000:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      MYSQL_USER: natac
      MYSQL_PASSWORD: campbell
    networks:
      - web
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.8.5
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - web
  # Wordpress
  webserver:
    depends_on:
      - db
    image: php:7.2.2-apache
    ports:
      - '8300:80'
    restart: always
    volumes:
      - ./php/:/var/www/html/
    stdin_open: true
    networks:
      - web
networks:
  web:
volumes:
  db_data:
